# -*- coding: utf-8 -*-
"""launch the app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dS770rO3MY7KblvoxngVM4QAVySLs3DE
"""

import os
from win32com.client import Dispatch

# Folder where shortcut and icon will be placed (same folder)
folder = os.path.abspath(".")
os.makedirs(folder, exist_ok=True)

# Shortcut and icon paths
shortcut_path = os.path.join(folder, "Voila Barplot Tool.lnk")
icon_filename = "bar_plot.ico"  # relative icon filename
icon_path = os.path.join(folder, icon_filename)

# Binder URL
url = "https://mybinder.org/v2/gh/deephms/voila-barplot-tool/main?urlpath=voila%2Frender%2Fapp.ipynb"

# Check if icon exists
if not os.path.exists(icon_path):
    print(f"Warning: Icon file not found at {icon_path}")
    print("The shortcut will use the default icon.")

# Create shortcut
shell = Dispatch('WScript.Shell')
shortcut = shell.CreateShortCut(shortcut_path)
shortcut.Targetpath = "C:\\Windows\\System32\\cmd.exe"
shortcut.Arguments = f'/c start "" "{url}"'
shortcut.IconLocation = icon_filename  # use relative path to icon
shortcut.save()

print(f"Shortcut created at {shortcut_path} with icon {icon_filename}")